---
- name: Multiple Handlers
  hosts: webserver
  become: true
  tasks:
    - name: execute a command-1
      command: hostname -s
      register: cmd_output
      notify:
        - Print output
        - Print a message
    - name: execute a command-2
      command: echo "restart service"
      notify:
        - Restart apache2
        - Restart docker
  handlers:
    - name: Print output
      debug: var=cmd_output.stdout
    - name: Print a message
      debug: msg="command executed successfully"
    - name: Restart apache2
      service: name=apache2 state=restarted
    - name: Restart docker
      service: name=docker state=restarted

