- name: variables in Ansible
  hosts: webserver
  become: true
  vars_files:
   - variables.yml
  tasks:
  - name: Install package on worker nodes
    package: name={{pkg_name}} state={{pkg_state}}
  - name: Create a empty file
    file: path={{file_path}} state={{file_state}}

